// frontend/src/features/mergeRequests/components/BoardColumn.jsx
import { MrCard } from "./MrCard.jsx";

export function BoardColumn(props) {
  const { idPrefix, mergeRequests, title } = props;

  const headingId = `columna-${idPrefix}-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`;

  return (
    <section
      aria-labelledby={headingId}
      className="bg-surface-raised border border-border-soft rounded-lg min-w-[250px] max-w-[250px] flex flex-col"
    >
      <div className="px-3 py-2 border-b border-border-soft flex items-center justify-between">
        <h3 className="text-[12px] font-semibold text-text-muted" id={headingId}>{title}</h3>
        <span className="text-[10.5px] text-text-faint bg-surface px-1.5 py-0.5 rounded-full">
          <span aria-hidden="true">{mergeRequests.length}</span>
          <span className="sr-only">{mergeRequests.length} merge requests</span>
        </span>
      </div>

      <ul className="overflow-y-auto p-2 flex flex-col gap-2 max-h-[60vh]" role="list">
        {mergeRequests.map((mr) => (
          <li key={mr.id}>
            <MrCard mr={mr} />
          </li>
        ))}
      </ul>
    </section>
  );
}

// frontend/src/components/BoardColumn.vue
<template>
  <div class="bg-surface border border-border rounded-lg min-w-[290px] max-w-[290px] flex flex-col max-h-[74vh]">
    <div class="px-3 py-2.5 border-b border-border-soft flex items-center justify-between">
      <span class="text-[12.5px] font-semibold flex items-center gap-1.5">
        <span class="text-text-faint font-bold">›</span>
        {{ title }}
      </span>
      <span class="text-[11px] text-text-muted bg-surface-raised px-2 py-0.5 rounded-full">
        {{ mergeRequests.length }}
      </span>
    </div>
    <div class="overflow-y-auto p-2 flex flex-col gap-2">
      <MrCard v-for="mr in mergeRequests" :key="mr.id" :mr="mr" />
      <div v-if="mergeRequests.length === 0" class="text-[12px] text-text-faint text-center py-5">
        Sin MRs
      </div>
    </div>
  </div>
</template>

<script setup>
import MrCard from './MrCard.vue'

defineProps({
  title: { type: String, required: true },
  mergeRequests: { type: Array, required: true },
})
</script>
