// frontend/src/components/BlockerBadge.vue
<template>
  <component
    :is="linkUrl ? 'a' : 'span'"
    :href="linkUrl || undefined"
    :target="linkUrl ? '_blank' : undefined"
    :rel="linkUrl ? 'noopener' : undefined"
    :class="badgeClasses"
    :title="tooltip"
    class="inline-flex items-center gap-1 text-[10px] font-semibold px-1.5 py-0.5 rounded no-underline"
  >
    <span v-html="icon"></span>
    <span>{{ label }}</span>
  </component>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  type: { type: String, required: true },
  data: { type: Object, required: true },
})

const icon = computed(() => {
  if (props.type === 'pipeline') {
    const s = props.data.status
    if (s === 'success') return '&#10003;'
    if (s === 'failed' || s === 'canceled') return '&#10007;'
    if (s === 'running' || s === 'pending') return '&#9679;'
    return '&#8211;'
  }
  if (props.type === 'threads') {
    return props.data.unresolvedCount > 0 ? '&#9993;' : '&#10003;'
  }
  if (props.type === 'approvals') {
    return props.data.status === 'approved' ? '&#10003;' : '&#9998;'
  }
  return ''
})

const label = computed(() => {
  if (props.type === 'pipeline') {
    const map = { success: 'CI OK', failed: 'CI Falló', running: 'CI...', pending: 'CI...', canceled: 'CI Cancel', none: 'Sin CI' }
    return map[props.data.status] || 'CI ?'
  }
  if (props.type === 'threads') {
    const c = props.data.unresolvedCount
    return c > 0 ? `${c} hilo${c > 1 ? 's' : ''}` : 'Hilos OK'
  }
  if (props.type === 'approvals') {
    if (props.data.status === 'unknown') return 'Approvals ?'
    return `${props.data.given}/${props.data.required}`
  }
  return ''
})

const tooltip = computed(() => {
  if (props.type === 'pipeline') return `Pipeline: ${props.data.status}`
  if (props.type === 'threads') return `${props.data.unresolvedCount} hilos sin resolver`
  if (props.type === 'approvals') {
    if (props.data.status === 'unknown') return 'No se pudo obtener info de approvals'
    const { given, required, approvers, hasLeadApproval } = props.data
    const parts = [`${given}/${required} aprobaciones`]
    if (approvers && approvers.length > 0) parts.push(`Aprobado por: ${approvers.join(', ')}`)
    if (!hasLeadApproval) parts.push('Falta aprobación del líder')
    return parts.join('\n')
  }
  return ''
})

const linkUrl = computed(() => {
  if (props.type === 'pipeline') return props.data.pipelineUrl || null
  return null
})

const badgeClasses = computed(() => {
  if (props.type === 'pipeline') {
    const s = props.data.status
    if (s === 'success') return 'bg-ready-soft text-ready'
    if (s === 'failed' || s === 'canceled') return 'bg-conflict-soft text-conflict'
    if (s === 'running' || s === 'pending') return 'bg-draft-soft text-draft'
    return 'bg-surface text-text-muted'
  }
  if (props.type === 'threads') {
    return props.data.unresolvedCount > 0
      ? 'bg-conflict-soft text-conflict'
      : 'bg-ready-soft text-ready'
  }
  if (props.type === 'approvals') {
    if (props.data.status === 'approved') return 'bg-ready-soft text-ready'
    if (props.data.status === 'pending') return 'bg-draft-soft text-draft'
    return 'bg-surface text-text-muted'
  }
  return 'bg-surface text-text-muted'
})
</script>

// frontend/src/features/mergeRequests/components/BlockerBadge.jsx
function iconFor(type, data) {
  if (type === "pipeline") {
    const status = data.status;
    if (status === "success") return "✓";
    if (status === "failed" || status === "canceled") return "✗";
    if (status === "running" || status === "pending") return "●";
    return "–";
  }
  if (type === "threads") return data.unresolvedCount > 0 ? "✉" : "✓";
  if (type === "approvals") return data.status === "approved" ? "✓" : "✎";
  if (type === "conflicts") return data.hasConflicts ? "✗" : "✓";
  return "";
}

function labelFor(type, data) {
  if (type === "pipeline") {
    const map = { success: "CI OK", failed: "CI Falló", running: "CI...", pending: "CI...", canceled: "CI Cancel", none: "Sin CI" };
    return map[data.status] || "CI ?";
  }
  if (type === "threads") {
    const count = data.unresolvedCount;
    return count > 0 ? `${count} hilo${count > 1 ? "s" : ""}` : "Hilos OK";
  }
  if (type === "approvals") {
    if (data.status === "unknown") return "Approvals ?";
    return `${data.given}/${data.required}`;
  }
  if (type === "conflicts") return data.hasConflicts ? "Con conflictos" : "Sin conflictos";
  return "";
}

function tooltipFor(type, data) {
  if (type === "pipeline") return `Pipeline: ${data.status}`;
  if (type === "threads") return `${data.unresolvedCount} hilos sin resolver`;
  if (type === "approvals") {
    if (data.status === "unknown") return "No se pudo obtener info de approvals";
    const { given, required, approvers, hasLeadApproval } = data;
    const parts = [`${given}/${required} aprobaciones`];
    if (approvers && approvers.length > 0) parts.push(`Aprobado por: ${approvers.join(", ")}`);
    if (!hasLeadApproval) parts.push("Falta aprobación del líder");
    return parts.join("\n");
  }
  if (type === "conflicts") {
    return data.hasConflicts ? "Tiene conflictos de merge" : "Sin conflictos de merge";
  }
  return "";
}

function badgeClasses(type, data) {
  if (type === "pipeline") {
    const status = data.status;
    if (status === "success") return "bg-ready-soft text-ready";
    if (status === "failed" || status === "canceled") return "bg-conflict-soft text-conflict";
    if (status === "running" || status === "pending") return "bg-draft-soft text-draft";
    return "bg-surface text-text-muted";
  }
  if (type === "threads") {
    return data.unresolvedCount > 0 ? "bg-conflict-soft text-conflict" : "bg-ready-soft text-ready";
  }
  if (type === "approvals") {
    if (data.status === "approved") return "bg-ready-soft text-ready";
    if (data.status === "pending") return "bg-draft-soft text-draft";
    return "bg-surface text-text-muted";
  }
  if (type === "conflicts") {
    return data.hasConflicts ? "bg-conflict-soft text-conflict" : "bg-ready-soft text-ready";
  }
  return "bg-surface text-text-muted";
}

export function BlockerBadge(props) {
  const { data, type } = props;

  const linkUrl = type === "pipeline" ? data.pipelineUrl || null : null;
  const tooltip = tooltipFor(type, data);
  const Tag = linkUrl ? "a" : "span";

  return (
    <Tag
      aria-label={`${tooltip}${linkUrl ? ". Abre en una pestaña nueva." : ""}`}
      className={`${badgeClasses(type, data)} inline-flex items-center gap-1 text-[11px] font-semibold px-1.5 py-0.5 rounded no-underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent`}
      href={linkUrl || undefined}
      rel={linkUrl ? "noopener" : undefined}
      target={linkUrl ? "_blank" : undefined}
      title={tooltip}
    >
      <span aria-hidden="true">{iconFor(type, data)}</span>
      <span>{labelFor(type, data)}</span>
      {linkUrl ? <span className="sr-only">(abre en una pestaña nueva)</span> : null}
    </Tag>
  );
}
