// frontend/src/features/mergeRequests/components/board_column/board_column.jsx

import { MrCard } from "../mr_card/mr_card.jsx";

import { Styles as AppStyles } from "../../../../app/app.styles.jsx";
import { Styles } from "./board_column.style.js";

export function BoardColumn(props) {
  const { idPrefix, mergeRequests, title } = props;

  const headingId = `columna-${idPrefix}-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`;

  return (
    <Styles.Column aria-labelledby={headingId}>
      <Styles.ColumnHeader>
        <Styles.ColumnTitle id={headingId}>{title}</Styles.ColumnTitle>

        <Styles.Count>
          <span aria-hidden="true">{mergeRequests.length}</span>
          <AppStyles.VisuallyHidden>{mergeRequests.length} merge requests</AppStyles.VisuallyHidden>
        </Styles.Count>
      </Styles.ColumnHeader>

      <Styles.CardList role="list">
        {mergeRequests.map((mr) => (
          <li key={mr.id}>
            <MrCard mr={mr} />
          </li>
        ))}
      </Styles.CardList>
    </Styles.Column>
  );
}

// frontend/src/features/mergeRequests/components/BoardColumn.vue
<template>
  <section class="bg-surface-raised border border-border-soft rounded-lg min-w-[250px] max-w-[250px] flex flex-col" :aria-labelledby="headingId">
    <div class="px-3 py-2 border-b border-border-soft flex items-center justify-between">
      <h3 :id="headingId" class="text-[12px] font-semibold text-text-muted">{{ title }}</h3>
      <span class="text-[10.5px] text-text-faint bg-surface px-1.5 py-0.5 rounded-full">
        <span aria-hidden="true">{{ mergeRequests.length }}</span>
        <span class="sr-only">{{ mergeRequests.length }} merge requests</span>
      </span>
    </div>
    <ul class="overflow-y-auto p-2 flex flex-col gap-2 max-h-[60vh]" role="list">
      <li v-for="mr in mergeRequests" :key="mr.id">
        <MrCard :mr="mr" />
      </li>
    </ul>
  </section>
</template>

<script setup>
import { computed } from 'vue'
import MrCard from './MrCard.vue'

const props = defineProps({
  title: { type: String, required: true },
  idPrefix: { type: String, required: true },
  mergeRequests: { type: Array, required: true },
})

const headingId = computed(() => `columna-${props.idPrefix}-${props.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`)
</script>
